# Note: The first part of this file can be modified in place, but the latter part is autogenerated by the boilerplate.py script. `matplotlib.pyplot` is a state-based interface to matplotlib. It provides a MATLAB-like way of plotting.
#pyplot is mainly intended for interactive plots and simple cases of programmatic plot generation:
#Referance MLGuide p 71..
#Peadar O Cathain 03 May 2019

#This program will plot a scatter plot

import numpy as np
#import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris =load_iris() # load dataset
#print("keys:", iris.keys())
#print ("Data shape" iris.data.shape)
#print ("Target shape", iris.target.shape)
print (iris[:4])
#syntaxError: reccommend object-oriented API for complax ploys???